version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    
  backend:
    build: ./backend
    posts:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mango:6
    container_name: mongo
    ports:
      - "27017:27017"
    wolumes:
      - ./db:/data/db
